# 예제 B.4 플러그인을 로컬 ZIP 파일에서 수동으로 설치하기

bin/plugin --url file:///downloads/elasticsearch-head.zip --install head
# -> Installing head...
# Trying file:/downloads/elasticsearch-head.zip...
# Donwloading ..........DONE
# Installed head into /Users/hinmanm/ies/elasticsearch-1.5.1/plugins/head
# Identified as a _site plugin, moving to _site structure ...
